"""optisim public package interface."""

from optisim.analytics import TrajectoryMetrics, analyze_trajectory, compare_trajectories
from optisim.batch import BatchConfig, BatchResult, BatchRunner, BatchTaskResult, run_batch
from optisim.behavior import BTStatus, BehaviorTreeBuilder, BehaviorTreeExecutor
from optisim.bimanual import BimanualCoordinator, BimanualTask, CooperativeManipulation, TaskPresets
from optisim.core import ActionPrimitive, TaskComposer, TaskDefinition, ValidationReport
from optisim.dynamics import (
    ConstraintSet,
    ConstraintViolation,
    DynamicsReport,
    DynamicsValidator,
    JointTorqueLimit,
    PayloadConstraint,
    RigidBodyState,
    TaskEnergyProfile,
    WorkspaceConstraint,
)
from optisim.grasp import (
    ContactPatch,
    ContactPoint,
    GraspExecutor,
    GraspPlanner,
    GraspPose,
    GraspResult,
    Gripper,
    GripperType,
    default_parallel_jaw,
    default_suction,
    default_three_finger,
    force_closure,
    friction_cone_check,
    grasp_wrench_space,
    min_resisted_wrench,
    slip_margin,
    surface_contacts,
)
from optisim.estimation import EKFConfig, RobotState, StateEstimationPipeline, build_estimator
from optisim.library import TaskCatalog
from optisim.multi import AssignmentValidator, Dependency, MultiRobotRecord, RobotFleet, TaskAssignment, TaskCoordinator
from optisim.mpc import FootstepPlanner, HumanoidMPC, MPCConfig, MPCSolution, build_humanoid_mpc
from optisim.perception import PerceptionPipeline, PointCloud, PoseEstimate, build_perception_pipeline
from optisim.planning import MotionPlanner, PlanningResult, RRTConfig
from optisim.reactive import (
    ContactPhase,
    ManipulationFSM,
    ReactiveConfig,
    ReactiveController,
    ReactiveExecutionResult,
    ReactiveState,
    run_reactive_manipulation,
)
from optisim.robot import DemoHumanoidSpec, HumanoidSpec, RobotModel, build_demo_humanoid, build_humanoid_model
from optisim.scenario import (
    ScenarioConfig,
    ScenarioResult,
    ScenarioRunner,
    ScenarioStepResult,
    SensorReading,
)
from optisim.sensors import (
    DepthCameraSensor,
    ForceTorqueSensor,
    IMUSensor,
    JointEncoderArray,
    ProximitySensor,
    SensorNoise,
    SensorSuite,
)
from optisim.safety import (
    EmergencyStop,
    JointSafetyLimit,
    SafetyConfig,
    SafetyMonitor,
    SafetyViolation,
    SafetyZone,
    ZoneType,
)
from optisim.sim import ExecutionEngine, WorldState
from optisim.trajopt import TrajOptConfig, TrajOptResult, TrajectoryOptimizer, optimize_path
from optisim.wbc import (
    BalanceTask,
    EndEffectorTask,
    JointLimitTask,
    PostureTask,
    WBCController,
    WBCSolution,
    WBCTask,
    build_wbc_controller,
)

__all__ = [
    "TrajectoryMetrics",
    "analyze_trajectory",
    "compare_trajectories",
    "BatchConfig",
    "BatchResult",
    "BatchRunner",
    "BatchTaskResult",
    "run_batch",
    "BTStatus",
    "BehaviorTreeBuilder",
    "BehaviorTreeExecutor",
    "BimanualCoordinator",
    "BimanualTask",
    "CooperativeManipulation",
    "TaskPresets",
    "ActionPrimitive",
    "TaskComposer",
    "TaskDefinition",
    "ConstraintSet",
    "ConstraintViolation",
    "DynamicsReport",
    "DynamicsValidator",
    "JointTorqueLimit",
    "PayloadConstraint",
    "RigidBodyState",
    "TaskEnergyProfile",
    "WorkspaceConstraint",
    "ContactPatch",
    "ContactPoint",
    "GraspExecutor",
    "GraspPlanner",
    "GraspPose",
    "GraspResult",
    "Gripper",
    "GripperType",
    "default_parallel_jaw",
    "default_suction",
    "default_three_finger",
    "force_closure",
    "friction_cone_check",
    "grasp_wrench_space",
    "min_resisted_wrench",
    "slip_margin",
    "surface_contacts",
    "RobotState",
    "EKFConfig",
    "StateEstimationPipeline",
    "build_estimator",
    "TaskCatalog",
    "AssignmentValidator",
    "Dependency",
    "MultiRobotRecord",
    "RobotFleet",
    "TaskAssignment",
    "TaskCoordinator",
    "MPCConfig",
    "MPCSolution",
    "HumanoidMPC",
    "FootstepPlanner",
    "build_humanoid_mpc",
    "PointCloud",
    "PoseEstimate",
    "PerceptionPipeline",
    "build_perception_pipeline",
    "ValidationReport",
    "MotionPlanner",
    "PlanningResult",
    "RRTConfig",
    "ContactPhase",
    "ManipulationFSM",
    "ReactiveConfig",
    "ReactiveController",
    "ReactiveExecutionResult",
    "ReactiveState",
    "run_reactive_manipulation",
    "DemoHumanoidSpec",
    "HumanoidSpec",
    "RobotModel",
    "build_demo_humanoid",
    "build_humanoid_model",
    "ScenarioConfig",
    "ScenarioResult",
    "ScenarioRunner",
    "ScenarioStepResult",
    "SensorReading",
    "DepthCameraSensor",
    "ForceTorqueSensor",
    "IMUSensor",
    "JointEncoderArray",
    "ProximitySensor",
    "SensorNoise",
    "SensorSuite",
    "EmergencyStop",
    "JointSafetyLimit",
    "SafetyConfig",
    "SafetyMonitor",
    "SafetyViolation",
    "SafetyZone",
    "ZoneType",
    "ExecutionEngine",
    "WorldState",
    "TrajOptConfig",
    "TrajOptResult",
    "TrajectoryOptimizer",
    "optimize_path",
    "WBCTask",
    "PostureTask",
    "EndEffectorTask",
    "BalanceTask",
    "JointLimitTask",
    "WBCController",
    "WBCSolution",
    "build_wbc_controller",
]

__version__ = "0.4.0"
